server:
  port: 8080


#eureka:
#  client:
#   serviceUrl:
#      defaultZone: http://localhost:8100/eureka/

#zuul:
#  eureka:
#    provider:
#      semaphore:
#        maxSemaphores: 1000

zuul:
  routes:
      user:
        path: /user/**
        url: http://localhost:9002/
      store:
        path: /store/**
        url: http://localhost:9001/
#ribbon:
#  eureka:
#    enabled: false